### ISSUE TITLE
no method references support

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#2]
The following is the stacktrace when running the following code:
`show(IntStream.range(0, 10).mapToObj(String::valueOf))`
```
java.lang.RuntimeException: JSExprEval.evalMethodRef() not implemented
        at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:109)
        at javakit.runner.JSExprEval.evalExprDot(JSExprEval.java:440)
        at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:67)
        at javakit.runner.JSExprEval.evalMethodCallExpr(JSExprEval.java:215)
        at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:75)
        at javakit.runner.JSExprEval.evalExprDot(JSExprEval.java:440)
        at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:67)
        at javakit.runner.JSExprEval.evalExprDot(JSExprEval.java:436)
        at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:67)
        at javakit.runner.JSExprEval.evalMethodCallExpr(JSExprEval.java:215)
        at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:75)
        at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:49)
        at javakit.runner.JSStmtEval.evalExpr(JSStmtEval.java:424)
        at javakit.runner.JSStmtEval.evalExprStmt(JSStmtEval.java:186)
        at javakit.runner.JSStmtEval.evalStmt(JSStmtEval.java:110)
        at javakit.runner.JSStmtEval.evalExecutable(JSStmtEval.java:52)
        at javakit.runner.JavaShell.evalStatement(JavaShell.java:123)
        at javakit.runner.JavaShell.runJavaCode(JavaShell.java:83)
        at snapcode.apptools.EvalToolRunner.runAppImpl(EvalToolRunner.java:62)
        at snapcode.apptools.EvalToolRunner.lambda$runApp$0(EvalToolRunner.java:42)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by reportmill** [comment]
Method references are supported now!
<img width="895" alt="MethodRefs" src="https://github.com/reportmill/SnapCode/assets/9698378/76a57c0b-24f7-4624-b588-7c97be891168">

**Comment by mmkathurima** [comment]
Hello @reportmill 

The following shows errors in the valueOf method and the collect method:
```java
System.out.println(Arrays.stream(stream).mapToObj(String::valueOf).collect(Collectors.joining("")));
```

**Comment by reportmill** [comment]
Thanks for reporting this! I assumed your 'stream' variable was an int array, and boiled the problem down to this code:

```
int[] intArray = new int[] { 1, 2, 3 };
IntStream stream = Arrays.stream(intArray);
```

Which resulted in SnapCode complaining, "Invalid assignment type". I found a bug where SnapCode was mistakenly choosing the Arrays.stream(long[]) method instead of Array.stream(int[]). This was an easy fix and should fix a number of other cases as well!
