### ISSUE TITLE
System.out.printf or System.out.format is buggy

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#3]
- First of all `\n` is printed as is. 
- `System.out.printf` or `System.out.format` requires separate `System.out.println()` since the `stdout` needs flushing.
```java
IntStream s = IntStream.range(1, 10);
int[] array = s.toArray();
for (int j = 0; j < Arrays.stream(array).count(); j++) {
    array[j] = new Random().nextInt(100);
    System.out.println(array[j]);
}
int max = array[0];
int min = array[0];
for (int j = 0; j < Arrays.stream(array).count(); j++) {
    if (array[j] > max) {
        max = array[j];
    } else if (array[j] < min) {
        min = array[j];
    }
}

System.out.printf("\n\n%d\n", max);
System.out.println(min);
```
yields `\n\n95\n21`

**Comment by reportmill** [comment]
I fixed this one - I just needed at convert 'escaped' string literals in code to non-escaped strings. I also needed to flush the console output at program end.

I may do more work on this - my output console should perhaps be grouping multiple lines of output in the same box instead of separating each line into it's own box.

Also, the download links have been updated for new month: https://reportmill.com/SnapCode/download.html

**Comment by mmkathurima** [comment]
Rerunning the code referenced below causes the stacktrace at the bottom:


> * First of all `\n` is printed as is.
> * `System.out.printf` or `System.out.format` requires separate `System.out.println()` since the `stdout` needs flushing.
> 
> ```java
> IntStream s = IntStream.range(1, 10);
> int[] array = s.toArray();
> for (int j = 0; j < Arrays.stream(array).count(); j++) {
>     array[j] = new Random().nextInt(100);
>     System.out.println(array[j]);
> }
> int max = array[0];
> int min = array[0];
> for (int j = 0; j < Arrays.stream(array).count(); j++) {
>     if (array[j] > max) {
>         max = array[j];
>     } else if (array[j] < min) {
>         min = array[j];
>     }
> }
> 
> System.out.printf("\n\n%d\n", max);
> System.out.println(min);
> ```
> 
> yields `\n\n95\n21`

```
java.lang.reflect.InaccessibleObjectException: Unable to make public final int[] java.util.stream.IntPipeline.toArray() accessible: module java.base does not "opens java.util.stream" to unnamed module @65373624
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at javakit.runner.JSExprEvalUtils.invokeMethod(JSExprEvalUtils.java:319)
	at javakit.runner.JSExprEval.evalMethodCallExpr(JSExprEval.java:232)
	at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:70)
	at javakit.runner.JSExprEval.evalExprDot(JSExprEval.java:437)
	at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:62)
	at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:44)
	at javakit.runner.JSExprEval.evalVarDeclExpr(JSExprEval.java:598)
	at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:74)
	at javakit.runner.JSExprEval.evalExpr(JSExprEval.java:44)
	at javakit.runner.JSStmtEval.evalExpr(JSStmtEval.java:433)
	at javakit.runner.JSStmtEval.evalExprStmt(JSStmtEval.java:182)
	at javakit.runner.JSStmtEval.evalStmt(JSStmtEval.java:110)
	at javakit.runner.JSStmtEval.evalExecutable(JSStmtEval.java:52)
	at javakit.runner.JavaShell.evalStatement(JavaShell.java:129)
	at javakit.runner.JavaShell.runJavaCode(JavaShell.java:88)
	at snapcode.apptools.EvalToolRunner.runAppImpl(EvalToolRunner.java:123)
	at snapcode.apptools.EvalToolRunner.lambda$runApp$0(EvalToolRunner.java:80)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by reportmill** [comment]
I think this is a problem running SnapCode with Java 9+. SnapCode really only supports Java 8 for now. I should be able to support Java 9+ in a couple months.

In the meantime, I've added a new link to download a desktop app version of SnapCode on the download page: https://reportmill.com/SnapCode/download.html . If you run via the desktop app, you'll automatically get Java 8.
